### ISSUE TITLE
Offline installation

### ISSUE THREAD

**Issue by frjariello** [adamzman/NodeRed_Niagara_Obix_Node#14]
Hi,
I'm trying to do offline installation with this [tgz](https://registry.npmjs.org/node-red-contrib-obix-niagara-connector/-/node-red-contrib-obix-niagara-connector-3.1.1.tgz) package, but I get this error **_ERR! code EAI_AGAIN_** which I think is due to no internet connection, is there a way to install it offline? Thanks

**Comment by adamzman** [comment]
I didn't believe there is a way to install while being offline. Sorry I couldn't help more.
